title: Jure Vraničar
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4464541834313422
  brandStrength: 0.8051232150755823
  rhythmicContrast: 0.4171624139416963
  brandColors:
    - '#A7304F'
    - '#F46D8D'
    - '#F39EB5'
    - '#081028'
    - '#F0CEB7'
  lightness: 0.2697323220781982
typography_spectrum: 0.1849049490410835
description: psihoterapevt
layout_spectrum: 1
name: jurevranicar.com
